/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void fwButton_click1(GButton source, GEvent event) { //_CODE_:fwButton:339083:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
  myPort.write('w');
} //_CODE_:fwButton:339083:

public void leftButton_click1(GButton source, GEvent event) { //_CODE_:leftButton:987253:
  println("button2 - GButton >> GEvent." + event + " @ " + millis());
  myPort.write('a');
} //_CODE_:leftButton:987253:

public void rightButton_click1(GButton source, GEvent event) { //_CODE_:rightButton:309864:
  println("button3 - GButton >> GEvent." + event + " @ " + millis());
  myPort.write('d');
} //_CODE_:rightButton:309864:

public void bwButton_click1(GButton source, GEvent event) { //_CODE_:bwButton:525324:
  println("button4 - GButton >> GEvent." + event + " @ " + millis());
  myPort.write('s');
} //_CODE_:bwButton:525324:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  fwButton = new GButton(this, 168, 62, 50, 30);
  fwButton.setText("W");
  fwButton.addEventHandler(this, "fwButton_click1");
  leftButton = new GButton(this, 116, 100, 50, 30);
  leftButton.setText("A");
  leftButton.addEventHandler(this, "leftButton_click1");
  rightButton = new GButton(this, 218, 100, 50, 30);
  rightButton.setText("D");
  rightButton.addEventHandler(this, "rightButton_click1");
  bwButton = new GButton(this, 166, 133, 50, 30);
  bwButton.setText("S");
  bwButton.addEventHandler(this, "bwButton_click1");
}

// Variable declarations 
// autogenerated do not edit
GButton fwButton; 
GButton leftButton; 
GButton rightButton; 
GButton bwButton; 
